"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-06

Full schema per MERIDIAN_SYSTEM_DESIGN.md section 5. Hand-written (not
autogenerated) so every constraint and the `current_mastery` view are
explicit and reviewable. Reversible: downgrade drops everything this
creates, in reverse dependency order.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("settings", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "prayer_times",
        sa.Column("date", sa.Date(), primary_key=True),
        sa.Column("fajr", sa.Time(), nullable=False),
        sa.Column("sunrise", sa.Time(), nullable=False),
        sa.Column("zuhr", sa.Time(), nullable=False),
        sa.Column("asr", sa.Time(), nullable=False),
        sa.Column("maghrib", sa.Time(), nullable=False),
        sa.Column("isha", sa.Time(), nullable=False),
    )

    op.create_table(
        "time_blocks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("start_spec", sa.String(), nullable=False),
        sa.Column("end_spec", sa.String(), nullable=False),
        sa.Column("start_resolved", sa.Time(), nullable=True),
        sa.Column("end_resolved", sa.Time(), nullable=True),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("planned_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="NOT DONE"),
        sa.Column("actual_minutes", sa.Integer(), nullable=True),
        sa.Column("energy_before", sa.Integer(), nullable=True),
        sa.Column("focus", sa.Integer(), nullable=True),
        sa.Column("deep_work", sa.Boolean(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("what_to_do", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("user_id", "date", "seq", name="uq_time_blocks_user_date_seq"),
        sa.CheckConstraint("tier IN ('T1','T2','T3','T4')", name="ck_time_blocks_tier"),
        sa.CheckConstraint(
            "status IN ('DONE','NOT DONE','PARTIAL','RESCHEDULED')", name="ck_time_blocks_status"
        ),
    )
    op.create_index("ix_time_blocks_user_id", "time_blocks", ["user_id"])
    op.create_index("ix_time_blocks_date", "time_blocks", ["date"])

    op.create_table(
        "problems",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("lc_number", sa.Integer(), nullable=False, unique=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False, unique=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("is_neetcode150", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_blind75", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("freq_meta", sa.Integer(), nullable=True),
        sa.Column("freq_amazon", sa.Integer(), nullable=True),
        sa.Column("freq_google", sa.Integer(), nullable=True),
    )
    op.create_index("ix_problems_pattern", "problems", ["pattern"])

    op.create_table(
        "curriculum",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("problem_id", sa.Integer(), sa.ForeignKey("problems.id"), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
    )
    op.create_index("ix_curriculum_problem_id", "curriculum", ["problem_id"])
    op.create_index("ix_curriculum_scheduled_date", "curriculum", ["scheduled_date"])

    op.create_table(
        "mistakes",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("track", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("what_went_wrong", sa.String(), nullable=False),
        sa.Column("root_cause", sa.String(), nullable=False),
        sa.Column("correct_thinking", sa.String(), nullable=True),
        sa.Column("memory_hook", sa.String(), nullable=True),
        sa.Column("redo_date", sa.Date(), nullable=True),
        sa.Column("redo_result", sa.String(), nullable=True),
    )
    op.create_index("ix_mistakes_user_id", "mistakes", ["user_id"])
    op.create_index("ix_mistakes_root_cause", "mistakes", ["root_cause"])

    op.create_table(
        "problem_attempts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("problem_id", sa.Integer(), sa.ForeignKey("problems.id"), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("mastery_level", sa.String(), nullable=False),
        sa.Column("hint_used", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("key_insight", sa.String(), nullable=True),
        sa.Column("mistake_id", sa.Integer(), sa.ForeignKey("mistakes.id"), nullable=True),
        sa.CheckConstraint("mastery_level ~ '^L[0-6]$'", name="ck_problem_attempts_mastery"),
    )
    op.create_index("ix_problem_attempts_user_id", "problem_attempts", ["user_id"])
    op.create_index("ix_problem_attempts_problem_id", "problem_attempts", ["problem_id"])
    op.create_index("ix_problem_attempts_attempted_at", "problem_attempts", ["attempted_at"])

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("overdue_days", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_result", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "subject_type IN ('problem','vocab','ml_concept','mistake')",
            name="ck_reviews_subject_type",
        ),
    )
    op.create_index("ix_reviews_user_id", "reviews", ["user_id"])
    op.create_index("ix_reviews_due_date", "reviews", ["due_date"])

    op.create_table(
        "mocks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("company_mode", sa.String(), nullable=False),
        sa.Column("round_type", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("score_coding", sa.Integer(), nullable=True),
        sa.Column("score_ml", sa.Integer(), nullable=True),
        sa.Column("score_sysdesign", sa.Integer(), nullable=True),
        sa.Column("score_comms", sa.Integer(), nullable=True),
        sa.Column("top_weakness", sa.String(), nullable=True),
        sa.Column("next_action", sa.String(), nullable=True),
    )
    op.create_index("ix_mocks_user_id", "mocks", ["user_id"])

    op.create_table(
        "thesis_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("milestone", sa.String(), nullable=True),
        sa.Column("work_summary", sa.String(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("output_type", sa.String(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
    )
    op.create_index("ix_thesis_log_user_id", "thesis_log", ["user_id"])

    op.create_table(
        "vocab_words",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("definition", sa.String(), nullable=False),
        sa.Column("example_sentence", sa.String(), nullable=True),
        sa.Column("date_introduced", sa.Date(), nullable=False),
    )
    op.create_index("ix_vocab_words_user_id", "vocab_words", ["user_id"])

    op.create_table(
        "recovery_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("mood", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("recovery_score", sa.Float(), nullable=True),
    )
    op.create_index("ix_recovery_log_user_id", "recovery_log", ["user_id"])

    op.create_table(
        "nutrition_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("water_ml", sa.Integer(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("nutrition_score", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
    )
    op.create_index("ix_nutrition_log_user_id", "nutrition_log", ["user_id"])

    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("recipe_ref", sa.String(), nullable=True),
    )

    op.create_table(
        "meal_plan",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(), nullable=False),
        sa.Column("meal_id", sa.Integer(), sa.ForeignKey("meals.id"), nullable=False),
    )
    op.create_index("ix_meal_plan_user_id", "meal_plan", ["user_id"])

    op.create_table(
        "reading_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False, server_default="book"),
        sa.Column("progress_note", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
    )
    op.create_index("ix_reading_log_user_id", "reading_log", ["user_id"])

    op.create_table(
        "time_leaks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("root_cause", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
    )
    op.create_index("ix_time_leaks_user_id", "time_leaks", ["user_id"])
    op.create_index("ix_time_leaks_trigger", "time_leaks", ["trigger"])

    op.create_table(
        "patterns",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(), nullable=False, unique=True),
        sa.Column("cues", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
    )

    op.create_table(
        "operating_rules",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("key", sa.String(), nullable=False, unique=True),
        sa.Column("rule_text", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
    )

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(), nullable=False),
        sa.UniqueConstraint("user_id", "key", name="uq_settings_user_key"),
    )
    op.create_index("ix_settings_user_id", "settings", ["user_id"])

    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("claim", sa.String(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column("effect_size", sa.Numeric(), nullable=True),
        sa.Column("suggested_action", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="new"),
        sa.CheckConstraint("confidence IN ('low','medium','high')", name="ck_observations_confidence"),
        sa.CheckConstraint(
            "status IN ('new','accepted','dismissed','stale')", name="ck_observations_status"
        ),
    )
    op.create_index("ix_observations_user_id", "observations", ["user_id"])
    op.create_index("ix_observations_detected_at", "observations", ["detected_at"])
    op.create_index("ix_observations_kind", "observations", ["kind"])

    # Mastery is a property of the latest attempt, never a mutable column
    # on `problems` (design doc 5.2) — this view is how "current mastery"
    # is read everywhere else.
    op.execute(
        """
        CREATE VIEW current_mastery AS
        SELECT DISTINCT ON (user_id, problem_id) user_id, problem_id, mastery_level, attempted_at
        FROM problem_attempts
        ORDER BY user_id, problem_id, attempted_at DESC;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS current_mastery;")
    for table in (
        "observations",
        "settings",
        "operating_rules",
        "patterns",
        "time_leaks",
        "reading_log",
        "meal_plan",
        "meals",
        "nutrition_log",
        "recovery_log",
        "vocab_words",
        "thesis_log",
        "mocks",
        "reviews",
        "problem_attempts",
        "mistakes",
        "curriculum",
        "problems",
        "time_blocks",
        "prayer_times",
        "users",
    ):
        op.drop_table(table)
