"""The 34-day topic-wise DSA sheet, resolved against real problem identities.

Each row records where the sheet places a problem (day, topic), its stated
difficulty, and the companies the sheet names. `lc` is filled in only where
the problem genuinely is that LeetCode problem; a classic algorithm with no
LeetCode entry (Dijkstra, KMP, Rat in a Maze, MCM, Heap Sort, …) carries
`lc=None` and `source="classic"` rather than a fabricated number or URL.

`extra` is the sheet's own truncation — "Quikr, Snapdeal, Synopsys +9"
becomes three names and extra=9. Nine unnamed companies is a fact; nine
invented names would not be.

Some sheet rows are the same problem listed twice on different days (Max
Area in Histogram / Largest Rectangle; Rotting Oranges under both Queues
and Graphs; Buy & Sell Stocks I under both Array and DP). They are kept as
written — the ingest deduplicates by identity, so the second occurrence
updates the same row instead of creating a near-duplicate.
"""
from __future__ import annotations

from typing import Any

# topic -> the NeetCode-taxonomy pattern a new problem defaults to, since
# `problems.pattern` is NOT NULL and is a solving-technique axis rather
# than a data-structure one.
TOPIC_DEFAULT_PATTERN: dict[str, str] = {
    "array": "arrays_hashing",
    "strings": "arrays_hashing",
    "binary_search": "binary_search",
    "recursion_backtracking": "backtracking",
    "linked_list": "linked_list",
    "stacks_queues": "stack",
    "binary_trees": "trees",
    "bst": "trees",
    "heaps": "heap",
    "tries": "tries",
    "graphs": "graphs",
    "dp": "dp_1d",
    "greedy": "greedy",
    "bit_math": "bit_manipulation",
}

# (day, topic, title, difficulty, companies, extra, lc, slug, pattern_override)
SHEET: list[tuple[int, str, str, str, list[str], int, int | None, str, str | None]] = [
    # ---------- Days 1-5: Array ----------
    (1, "array", "Majority Element", "Easy", ["Amazon", "Google"], 0, 169, "majority-element", None),
    (1, "array", "Repeat & Missing Number", "Easy", ["Amazon"], 0, None,
     "repeat-and-missing-number", None),
    (1, "array", "Merge 2 Sorted Arrays Without Extra Space", "Easy",
     ["Quikr", "Snapdeal", "Synopsys"], 9, 88, "merge-sorted-array", "two_pointers"),
    (1, "array", "Single Number", "Easy", ["Apple", "Amazon", "Microsoft"], 8, 136,
     "single-number", "bit_manipulation"),
    (1, "array", "Stock Buy & Sell", "Easy", ["Walmart", "Swiggy", "Google"], 15, 121,
     "best-time-to-buy-and-sell-stock", "sliding_window"),
    (1, "array", "Pow(x, n)", "Medium", ["Linkedin", "Amazon", "Meta"], 6, 50, "powx-n",
     "math_geometry"),
    (3, "array", "Next Permutation", "Medium", ["Uber", "Goldman Sachs", "Adobe"], 0, 31,
     "next-permutation", None),
    (3, "array", "Merge Overlapping Intervals", "Medium", ["Google"], 0, 56, "merge-intervals",
     "intervals"),
    (3, "array", "Longest Substring Without Repeating Characters", "Medium",
     ["Morgan Stanley", "Amazon"], 0, 3, "longest-substring-without-repeating-characters",
     "sliding_window"),
    (3, "array", "Set Matrix Zeroes", "Medium", ["Amazon", "Microsoft"], 0, 73,
     "set-matrix-zeroes", None),
    (3, "array", "Word Search", "Medium", ["Ola", "Goldman Sachs", "Google"], 0, 79,
     "word-search", "backtracking"),
    (3, "array", "Product of Array Except Self", "Medium", ["Ola", "Goldman Sachs", "Google"], 0,
     238, "product-of-array-except-self", None),
    (4, "array", "Subarray Sum Equals K", "Medium", ["Microsoft", "Snapdeal"], 0, 560,
     "subarray-sum-equals-k", None),
    (4, "array", "Find the Duplicate Number", "Medium", ["Apple", "Goldman Sachs", "IBM"], 2, 287,
     "find-the-duplicate-number", "linked_list"),
    (4, "array", "Count Inversions", "Hard", ["Google", "Amazon", "Salesforce"], 0, None,
     "count-inversions", None),
    (4, "array", "Spiral Matrix", "Medium", ["Flipkart", "Societe Generale", "Apple"], 0, 54,
     "spiral-matrix", None),
    (4, "array", "Search a 2D Matrix II", "Medium", ["Microsoft", "Oracle", "Amazon"], 3, 240,
     "search-a-2d-matrix-ii", "binary_search"),
    (5, "array", "Trapping Rain Water", "Hard", ["Samsung"], 0, 42, "trapping-rain-water",
     "two_pointers"),
    (5, "array", "Sliding Window Maximum", "Hard", ["Flipkart", "Google", "Microsoft"], 2, 239,
     "sliding-window-maximum", "sliding_window"),
    (5, "array", "Largest Rectangle In Histogram", "Hard", ["Meta", "Doordash", "Google"], 4, 84,
     "largest-rectangle-in-histogram", "stack"),
    (5, "array", "Reverse Pairs", "Hard", ["Adobe", "Apple", "Amazon"], 1, 493, "reverse-pairs",
     None),

    # ---------- Days 6-7: Strings ----------
    (6, "strings", "Valid Palindrome", "Easy", ["Morgan Stanley", "Amazon", "DE Shaw"], 5, 125,
     "valid-palindrome", "two_pointers"),
    (6, "strings", "Valid Anagram", "Easy", ["Flipkart", "Directi", "Media.Net"], 3, 242,
     "valid-anagram", None),
    (6, "strings", "Reverse Words in a String", "Medium", ["TCS", "Infosys", "Nvidia"], 5, 151,
     "reverse-words-in-a-string", None),
    (6, "strings", "Remove All Occurrences of a Substring", "Medium",
     ["IBM", "Microsoft", "Google"], 0, 1910, "remove-all-occurrences-of-a-substring", None),
    (6, "strings", "Permutation in String", "Medium", ["Adobe", "Goldman Sachs", "Uber"], 0, 567,
     "permutation-in-string", "sliding_window"),
    (6, "strings", "String Compression", "Medium", ["GoDaddy", "Amazon", "Salesforce"], 3, 443,
     "string-compression", "two_pointers"),
    (7, "strings", "Longest Common Prefix", "Easy", ["Google", "Meta", "TCS"], 5, 14,
     "longest-common-prefix", None),
    (7, "strings", "Group Anagrams", "Medium", ["Google", "Salesforce", "TCS"], 6, 49,
     "group-anagrams", None),
    (7, "strings", "Minimum Window Substring", "Hard", ["MakeMyTrip", "Flipkart", "Google"], 4, 76,
     "minimum-window-substring", "sliding_window"),
    (7, "strings", "KMP Algorithm (Pattern Matching)", "Hard", ["Google", "Amazon"], 0, None,
     "kmp-algorithm", None),
    (7, "strings", "Rabin-Karp Algorithm", "Hard", ["Microsoft"], 0, None, "rabin-karp-algorithm",
     None),

    # ---------- Day 8: Binary Search ----------
    (8, "binary_search", "Peak Index in a Mountain Array", "Medium",
     ["Google", "DE Shaw", "Meta"], 5, 852, "peak-index-in-a-mountain-array", None),
    (8, "binary_search", "Search in Rotated Sorted Array", "Medium",
     ["MakeMyTrip", "Visa", "Google"], 9, 33, "search-in-rotated-sorted-array", None),
    (8, "binary_search", "Single Element in a Sorted Array", "Medium",
     ["Infosys", "TCS", "Blinkit"], 5, 540, "single-element-in-a-sorted-array", None),
    (8, "binary_search", "Aggressive Cows", "Medium", ["Adobe"], 0, None, "aggressive-cows", None),
    (8, "binary_search", "Allocate Minimum Number of Pages", "Medium",
     ["Salesforce", "Google", "Amazon"], 0, None, "allocate-minimum-pages", None),
    (8, "binary_search", "Painter's Partition Problem", "Medium",
     ["Google", "Oracle", "Microsoft"], 1, None, "painters-partition", None),
    (8, "binary_search", "Median of Two Sorted Arrays", "Hard", ["Google", "Flipkart", "DE Shaw"],
     6, 4, "median-of-two-sorted-arrays", None),

    # ---------- Days 9-10: Recursion & Backtracking ----------
    (9, "recursion_backtracking", "Combination Sum", "Medium",
     ["Microsoft", "Amazon", "DE Shaw"], 3, 39, "combination-sum", None),
    (9, "recursion_backtracking", "Combination Sum II", "Medium",
     ["Oracle", "Microsoft", "Amazon"], 2, 40, "combination-sum-ii", None),
    (9, "recursion_backtracking", "Palindrome Partitioning", "Medium",
     ["Meta", "Microsoft", "Amazon"], 2, 131, "palindrome-partitioning", None),
    (9, "recursion_backtracking", "N Queens", "Hard", ["TCS", "Apple", "Citadel"], 6, 51,
     "n-queens", None),
    (9, "recursion_backtracking", "Sudoku Solver", "Hard", ["Citadel", "Oracle", "Microsoft"], 5,
     37, "sudoku-solver", None),
    (9, "recursion_backtracking", "M-Coloring Problem", "Medium", ["Amazon"], 0, None,
     "m-coloring-problem", None),
    (10, "recursion_backtracking", "Knight's Tour", "Medium", ["Meta", "Google", "Microsoft"], 1,
     None, "knights-tour", None),
    (10, "recursion_backtracking", "Subsets II", "Medium", ["Swiggy", "Apple", "Meta"], 7, 90,
     "subsets-ii", None),
    (10, "recursion_backtracking", "Merge Sort", "Easy", ["Infosys", "Oracle", "Adobe"], 4, None,
     "merge-sort", None),
    (10, "recursion_backtracking", "Rat in a Maze", "Medium", ["Amazon", "Microsoft"], 0, None,
     "rat-in-a-maze", None),

    # ---------- Days 11-12: Linked List ----------
    (11, "linked_list", "Middle of the Linked List", "Easy", ["Meta", "Amazon", "Google"], 3, 876,
     "middle-of-the-linked-list", None),
    (11, "linked_list", "Reverse Linked List", "Easy", ["Google", "PayPal", "Microsoft"], 8, 206,
     "reverse-linked-list", None),
    (11, "linked_list", "Linked List Cycle II (Remove Cycle)", "Medium",
     ["Amazon", "Oracle", "Paytm"], 2, 142, "linked-list-cycle-ii", None),
    (11, "linked_list", "Linked List Cycle", "Easy", ["Google", "Meta", "Cisco"], 4, 141,
     "linked-list-cycle", None),
    (11, "linked_list", "Merge Two Sorted Lists", "Easy", ["Synopsys", "FactSet", "Brocade"], 9,
     21, "merge-two-sorted-lists", None),
    (11, "linked_list", "Flatten a Multilevel Linked List", "Medium",
     ["Meta", "Apple", "Amazon"], 0, None, "flatten-a-linked-list", None),
    (12, "linked_list", "Palindrome Linked List", "Easy", ["Qualcomm", "Oracle", "Adobe"], 4, 234,
     "palindrome-linked-list", None),
    (12, "linked_list", "Copy List With Random Pointer", "Medium",
     ["Nvidia", "Intel", "Oracle"], 5, 138, "copy-list-with-random-pointer", None),
    (12, "linked_list", "Reverse Linked List II", "Medium", ["Uber", "Adobe", "Microsoft"], 3, 92,
     "reverse-linked-list-ii", None),
    (12, "linked_list", "Add Two Numbers", "Medium", ["Microsoft", "Amazon", "Oracle"], 5, 2,
     "add-two-numbers", None),
    (12, "linked_list", "Reverse Nodes in K Group", "Hard", ["Uber", "Salesforce", "Apple"], 4,
     25, "reverse-nodes-in-k-group", None),
    (12, "linked_list", "Rotate List", "Medium", ["Infosys", "Nvidia", "Meta"], 7, 61,
     "rotate-list", None),

    # ---------- Days 13-15: Stacks & Queues ----------
    (13, "stacks_queues", "Implement Stack Using Queues", "Easy", ["Google", "Oracle", "Adobe"], 4,
     225, "implement-stack-using-queues", None),
    (13, "stacks_queues", "Next Greater Element I", "Easy", ["Apple", "Microsoft", "Meta"], 5, 496,
     "next-greater-element-i", "arrays_hashing"),
    (13, "stacks_queues", "Implement Queue Using Stacks", "Easy", ["Adobe", "Amazon", "Google"], 3,
     232, "implement-queue-using-stacks", None),
    (13, "stacks_queues", "Valid Parentheses", "Easy", ["Amazon", "TCS", "JP Morgan"], 6, 20,
     "valid-parentheses", None),
    (13, "stacks_queues", "First Non-Repeating Character in a Stream", "Easy",
     ["Google", "TCS", "Meta"], 4, None, "first-non-repeating-in-stream", None),
    (13, "stacks_queues", "Reverse First K Elements of a Queue", "Easy",
     ["Amazon", "Amdocs", "Microsoft"], 0, None, "reverse-first-k-of-queue", None),
    (14, "stacks_queues", "Time Needed to Buy Tickets", "Easy", ["Uber", "Meta", "Microsoft"], 2,
     2073, "time-needed-to-buy-tickets", None),
    (14, "stacks_queues", "LRU Cache", "Medium", ["Amazon", "Miro", "Ebay"], 7, 146, "lru-cache",
     None),
    (14, "stacks_queues", "Min Stack", "Medium", ["Amazon", "Meta", "Nike"], 5, 155, "min-stack",
     None),
    (14, "stacks_queues", "Next Greater Element II", "Medium", ["Amazon", "Uber"], 0, 503,
     "next-greater-element-ii", None),
    (14, "stacks_queues", "The Celebrity Problem", "Medium", ["Google", "Linkedin", "Uber"], 4,
     None, "celebrity-problem", None),
    (15, "stacks_queues", "Rotting Oranges", "Medium", ["Amazon", "Flipkart", "Intuit"], 6, 994,
     "rotting-oranges", "graphs"),
    (15, "stacks_queues", "Sort a Stack", "Medium", ["Goldman Sachs", "IBM", "Intuit"], 2, None,
     "sort-a-stack", None),
    (15, "stacks_queues", "Online Stock Span", "Medium", ["Microsoft", "Google", "Amazon"], 3, 901,
     "online-stock-span", None),
    (15, "stacks_queues", "Gas Station (Circular Tour)", "Medium",
     ["Salesforce", "Adobe", "Oracle"], 7, 134, "gas-station", "greedy"),

    # ---------- Days 16-19: Binary Trees ----------
    (16, "binary_trees", "Binary Tree Preorder Traversal", "Easy",
     ["Salesforce", "Amazon", "Microsoft"], 3, 144, "binary-tree-preorder-traversal", None),
    (16, "binary_trees", "Binary Tree Level Order Traversal", "Medium",
     ["Amazon", "Google", "Oracle"], 5, 102, "binary-tree-level-order-traversal", None),
    (16, "binary_trees", "Binary Tree Inorder Traversal", "Easy", ["Adobe", "Uber", "Meta"], 3, 94,
     "binary-tree-inorder-traversal", None),
    (16, "binary_trees", "Minimum Distance Between BST Nodes", "Easy", ["Microsoft", "Google"], 0,
     783, "minimum-distance-between-bst-nodes", None),
    (16, "binary_trees", "Symmetric Tree", "Easy", ["Adobe", "Amazon", "Google"], 2, 101,
     "symmetric-tree", None),
    (16, "binary_trees", "Binary Tree Postorder Traversal", "Easy", ["Apple", "Adobe", "Google"],
     2, 145, "binary-tree-postorder-traversal", None),
    (17, "binary_trees", "Morris Inorder Traversal", "Easy", ["Uber", "Google", "Apple"], 3, None,
     "morris-inorder-traversal", None),
    (17, "binary_trees", "Diameter of Binary Tree", "Easy", ["Adobe", "Oracle", "Visa"], 4, 543,
     "diameter-of-binary-tree", None),
    (17, "binary_trees", "Same Tree", "Easy", ["Adobe", "Meta", "Apple"], 6, 100, "same-tree",
     None),
    (17, "binary_trees", "Subtree of Another Tree", "Easy",
     ["Microsoft", "Morgan Stanley", "Uber"], 3, 572, "subtree-of-another-tree", None),
    (17, "binary_trees", "Balanced Binary Tree", "Easy", ["Microsoft", "Adobe", "Uber"], 2, 110,
     "balanced-binary-tree", None),
    (18, "binary_trees", "Bottom View of a Binary Tree", "Medium",
     ["Amazon", "Google", "Adobe"], 1, None, "bottom-view-of-binary-tree", None),
    (18, "binary_trees", "Top View of a Binary Tree", "Medium",
     ["Accolite", "Flipkart", "Oracle"], 4, None, "top-view-of-binary-tree", None),
    (18, "binary_trees", "Lowest Common Ancestor of a Binary Tree", "Medium",
     ["Morgan Stanley", "Salesforce", "Flipkart"], 6, 236,
     "lowest-common-ancestor-of-a-binary-tree", None),
    (18, "binary_trees", "Kth Level of a Tree", "Medium", ["Meta", "Microsoft", "Google"], 2, None,
     "kth-level-of-tree", None),
    (18, "binary_trees", "Construct Binary Tree From Preorder And Inorder Traversal", "Medium",
     ["Apple", "Microsoft", "Amazon"], 3, 105,
     "construct-binary-tree-from-preorder-and-inorder-traversal", None),
    (18, "binary_trees", "Transform to Sum Tree", "Medium", ["Amazon", "Microsoft", "Ebay"], 1,
     None, "transform-to-sum-tree", None),
    (19, "binary_trees", "Flatten Binary Tree to Linked List", "Medium",
     ["Microsoft", "Apple", "Google"], 4, 114, "flatten-binary-tree-to-linked-list", None),
    (19, "binary_trees", "Binary Tree Maximum Path Sum", "Hard",
     ["Goldman Sachs", "Salesforce", "Oracle"], 4, 124, "binary-tree-maximum-path-sum", None),
    (19, "binary_trees", "Maximum Width of Binary Tree", "Medium",
     ["Amazon", "Google", "Adobe"], 2, 662, "maximum-width-of-binary-tree", None),
    (19, "binary_trees", "Construct Binary Tree From Inorder And Postorder Traversal", "Medium",
     ["Amazon", "Bloomberg", "Google"], 2, 106,
     "construct-binary-tree-from-inorder-and-postorder-traversal", None),
    (19, "binary_trees", "Binary Tree Zigzag Level Order Traversal", "Medium",
     ["Google", "Adobe", "Ebay"], 5, 103, "binary-tree-zigzag-level-order-traversal", None),
    (19, "binary_trees", "Kth Ancestor of a Node", "Hard", ["Microsoft", "Amazon", "Google"], 0,
     None, "kth-ancestor-of-a-node", None),

    # ---------- Days 20-22: BST ----------
    (20, "bst", "Kth Largest Element in a BST", "Easy", ["Amazon", "Adobe", "Salesforce"], 3, None,
     "kth-largest-element-in-a-bst", None),
    (20, "bst", "Convert Sorted Array to Binary Search Tree", "Easy",
     ["Adobe", "Airbnb", "Google"], 2, 108, "convert-sorted-array-to-binary-search-tree", None),
    (20, "bst", "Kth Smallest Element In a BST", "Medium", ["Uber", "Google", "Accolite"], 2, 230,
     "kth-smallest-element-in-a-bst", None),
    (20, "bst", "Lowest Common Ancestor of a Binary Search Tree", "Medium",
     ["Meta", "Apple", "Bloomberg"], 4, 235,
     "lowest-common-ancestor-of-a-binary-search-tree", None),
    (20, "bst", "Validate Binary Search Tree", "Medium", ["Citadel", "Uber", "Salesforce"], 5, 98,
     "validate-binary-search-tree", None),
    (21, "bst", "Recover Binary Search Tree", "Medium", ["Adobe", "Oracle", "Google"], 2, 99,
     "recover-binary-search-tree", None),
    (21, "bst", "Populating Next Right Pointers in Each Node", "Medium",
     ["Amazon", "Adobe", "Flipkart"], 2, 116, "populating-next-right-pointers-in-each-node", None),
    (21, "bst", "Construct BST from Preorder Traversal", "Medium",
     ["Adobe", "Google", "Microsoft"], 0, 1008,
     "construct-binary-search-tree-from-preorder-traversal", None),
    (21, "bst", "Binary Search Tree Iterator", "Medium", ["Adobe", "Linkedin", "Microsoft"], 1,
     173, "binary-search-tree-iterator", None),
    (21, "bst", "Flatten BST to a Sorted List", "Medium", ["Meta", "Nvidia", "Microsoft"], 1, None,
     "flatten-bst-to-sorted-list", None),
    (22, "bst", "Merge Two BSTs", "Hard", ["Bloomberg", "Microsoft"], 0, None, "merge-two-bsts",
     None),
    (22, "bst", "Serialize and Deserialize BST", "Hard", ["Meta", "Amazon", "Google"], 6, 449,
     "serialize-and-deserialize-bst", None),
    (22, "bst", "Inorder Predecessor in BST", "Medium", ["Flipkart", "Oracle", "Google"], 4, None,
     "inorder-predecessor-in-bst", None),
    (22, "bst", "Largest BST in a Binary Tree", "Medium", ["Microsoft", "Meta"], 0, None,
     "largest-bst-in-binary-tree", None),
    (22, "bst", "Inorder Successor in BST", "Medium", ["Microsoft", "Meta"], 0, 285,
     "inorder-successor-in-bst", None),

    # ---------- Day 23: Heaps ----------
    (23, "heaps", "Merge K Sorted Lists", "Easy", ["Cisco", "Amazon", "IBM"], 5, 23,
     "merge-k-sorted-lists", "linked_list"),
    (23, "heaps", "Top K Frequent Elements", "Medium", ["Salesforce", "Microsoft", "Amazon"], 4,
     347, "top-k-frequent-elements", "arrays_hashing"),
    (23, "heaps", "Find Median From Data Stream", "Hard", ["Pinterest", "Google", "Apple"], 6, 295,
     "find-median-from-data-stream", None),
    (23, "heaps", "Smallest Range Covering Elements from K Lists", "Hard",
     ["Phone Pe", "Flipkart", "DE Shaw"], 4, 632,
     "smallest-range-covering-elements-from-k-lists", None),
    (23, "heaps", "Kth Largest Element In An Array", "Medium",
     ["Meta", "Phone Pe", "Salesforce"], 2, 215, "kth-largest-element-in-an-array", None),
    (23, "heaps", "Heap Sort", "Medium", ["Oracle", "Google", "Amazon"], 5, None, "heap-sort",
     None),

    # ---------- Day 24: Tries ----------
    (24, "tries", "Word Break", "Medium", ["Flipkart", "Amazon", "Google"], 6, 139, "word-break",
     "dp_1d"),
    (24, "tries", "Implement Trie (Prefix Tree)", "Medium", ["Meta", "Nvidia", "Google"], 4, 208,
     "implement-trie-prefix-tree", None),
    (24, "tries", "Longest String With All Prefixes", "Medium", ["Google"], 0, None,
     "longest-string-with-all-prefixes", None),
    (24, "tries", "Implement a Phone Directory", "Medium", ["Google"], 0, None,
     "implement-a-phone-directory", None),

    # ---------- Days 25-28: Graphs ----------
    (25, "graphs", "Depth First Search (DFS) Traversal", "Medium",
     ["Samsung", "Intuit", "Amazon"], 1, None, "dfs-traversal", None),
    (25, "graphs", "Breadth First Search (BFS) Traversal", "Medium",
     ["Microsoft", "Samsung", "Adobe"], 4, None, "bfs-traversal", None),
    (25, "graphs", "Detect Cycle in an Undirected Graph (BFS)", "Medium",
     ["Visa", "Flipkart", "Amazon"], 4, None, "detect-cycle-undirected-bfs", None),
    (25, "graphs", "Detect Cycle in an Undirected Graph (DFS)", "Medium",
     ["Google", "Visa", "Oracle"], 4, None, "detect-cycle-undirected-dfs", None),
    (25, "graphs", "Detect Cycle in a Directed Graph (DFS)", "Medium",
     ["Microsoft", "Google", "Amazon"], 1, None, "detect-cycle-directed-dfs", None),
    (25, "graphs", "Detect Cycle in a Directed Graph (BFS)", "Medium",
     ["Google", "Amazon", "InMobi"], 1, None, "detect-cycle-directed-bfs", None),
    (26, "graphs", "Topological Sort (DFS)", "Medium",
     ["Visa", "Moonfrog Labs", "Morgan Stanley"], 7, None, "topological-sort-dfs", None),
    (26, "graphs", "Flood Fill", "Easy", ["Uber", "Amazon", "Yahoo"], 4, 733, "flood-fill", None),
    (26, "graphs", "Topological Sort (BFS / Kahn's)", "Medium",
     ["Amazon", "Moonfrog Labs", "Visa"], 7, None, "topological-sort-bfs", None),
    (26, "graphs", "Course Schedule II", "Medium", ["Nvidia", "Meta", "Microsoft"], 6, 210,
     "course-schedule-ii", None),
    (26, "graphs", "Cheapest Flights Within K Stops", "Medium", ["Apple", "Stripe", "Amazon"], 3,
     787, "cheapest-flights-within-k-stops", "advanced_graphs"),
    (26, "graphs", "Dijkstra's Algorithm", "Hard", ["Flipkart", "Microsoft"], 0, None,
     "dijkstras-algorithm", "advanced_graphs"),
    (27, "graphs", "Kruskal's Algorithm (MST)", "Hard", ["DE Shaw", "Uber", "Directi"], 3, None,
     "kruskals-algorithm", "advanced_graphs"),
    (27, "graphs", "Prim's Algorithm (MST)", "Hard", ["Microsoft", "Directi", "Uber"], 3, None,
     "prims-algorithm", "advanced_graphs"),
    (27, "graphs", "Clone Graph", "Medium", ["Google", "Amazon", "Meta"], 2, 133, "clone-graph",
     None),
    (27, "graphs", "Floyd-Warshall Algorithm", "Hard", ["Meta", "Amazon", "Microsoft"], 2, None,
     "floyd-warshall-algorithm", "advanced_graphs"),
    (27, "graphs", "Bellman-Ford Algorithm", "Hard", ["Directi", "Sharechat", "Microsoft"], 1,
     None, "bellman-ford-algorithm", "advanced_graphs"),
    (27, "graphs", "01 Matrix", "Medium", ["Linkedin", "Doordash", "Google"], 3, 542, "01-matrix",
     None),
    (28, "graphs", "Number of Islands", "Medium", ["Linkedin", "Amazon", "Meta"], 8, 200,
     "number-of-islands", None),
    (28, "graphs", "Is Graph Bipartite?", "Medium", ["Samsung", "Meta", "Pinterest"], 3, 785,
     "is-graph-bipartite", None),
    (28, "graphs", "Strongly Connected Components (Kosaraju's)", "Hard", ["Paytm"], 0, None,
     "strongly-connected-components-kosaraju", "advanced_graphs"),
    (28, "graphs", "Most Stones Removed with Same Row or Column", "Medium",
     ["Microsoft", "Amazon", "Google"], 0, 947, "most-stones-removed-with-same-row-or-column",
     "advanced_graphs"),
    (28, "graphs", "Number of Ways to Arrive at Destination", "Medium", ["Google", "Amazon"], 0,
     1976, "number-of-ways-to-arrive-at-destination", "advanced_graphs"),
    (28, "graphs", "Number of Provinces", "Medium", ["Amazon", "Meta", "Sprinklr"], 1, 547,
     "number-of-provinces", None),
    (28, "graphs", "Critical Connections in a Network", "Hard", ["Citadel", "Google", "Airbnb"], 1,
     1192, "critical-connections-in-a-network", "advanced_graphs"),

    # ---------- Days 29-32: DP ----------
    (29, "dp", "0-1 Knapsack", "Medium", ["Directi", "Morgan Stanley", "Oracle"], 8, None,
     "0-1-knapsack", "dp_2d"),
    (29, "dp", "Best Time to Buy And Sell Stock", "Easy",
     ["Amazon", "Directi", "Goldman Sachs"], 15, 121, "best-time-to-buy-and-sell-stock",
     "sliding_window"),
    (29, "dp", "Target Sum", "Medium", ["Myntra", "Meta", "Amazon"], 1, 494, "target-sum", "dp_2d"),
    (29, "dp", "Coin Change", "Medium", ["Salesforce", "Microsoft", "Intuit"], 5, 322,
     "coin-change", None),
    (29, "dp", "Unbounded Knapsack", "Medium", ["Google", "Amazon"], 0, None,
     "unbounded-knapsack", "dp_2d"),
    (30, "dp", "Longest Common Substring", "Medium",
     ["Amazon", "Microsoft", "Morgan Stanley"], 0, 718,
     "maximum-length-of-repeated-subarray", "dp_2d"),
    (30, "dp", "Longest Common Subsequence", "Medium", ["Oracle", "Amazon", "Google"], 3, 1143,
     "longest-common-subsequence", "dp_2d"),
    (30, "dp", "Longest Increasing Subsequence", "Medium",
     ["Salesforce", "Google", "Atlassian"], 5, 300, "longest-increasing-subsequence", None),
    (30, "dp", "Edit Distance", "Medium", ["Goldman Sachs", "Google", "TCS"], 4, 72,
     "edit-distance", "dp_2d"),
    (30, "dp", "Longest Palindromic Subsequence", "Medium", ["TCS", "Linkedin", "Amazon"], 3, 516,
     "longest-palindromic-subsequence", "dp_2d"),
    (30, "dp", "Best Time to Buy And Sell Stock II", "Medium", ["Amazon", "Adobe", "TCS"], 3, 122,
     "best-time-to-buy-and-sell-stock-ii", "greedy"),
    (31, "dp", "Nth Catalan Number", "Medium", ["Google", "Amazon"], 0, None,
     "nth-catalan-number", None),
    (31, "dp", "Unique Binary Search Trees", "Medium", ["Google", "Amazon", "Oracle"], 2, 96,
     "unique-binary-search-trees", None),
    (31, "dp", "Rod Cutting", "Hard", ["Phone Pe", "Apple", "Oracle"], 1, None, "rod-cutting",
     "dp_2d"),
    (31, "dp", "Palindrome Partitioning II (Min Cuts)", "Medium",
     ["Infosys", "Amazon", "Microsoft"], 2, 132, "palindrome-partitioning-ii", "dp_2d"),
    (31, "dp", "Matrix Chain Multiplication", "Hard", ["Walmart", "Flipkart"], 0, None,
     "matrix-chain-multiplication", "dp_2d"),
    (32, "dp", "Minimum Subset Sum Partition", "Hard", ["Google", "Uber", "Samsung"], 3, None,
     "minimum-subset-sum-partition", "dp_2d"),
    (32, "dp", "Maximum Product Subarray", "Medium", ["Meta", "Amazon", "Uber"], 3, 152,
     "maximum-product-subarray", None),
    (32, "dp", "Wildcard Matching", "Hard", ["Apple", "Microsoft", "Amazon"], 2, 44,
     "wildcard-matching", "dp_2d"),
    (32, "dp", "Longest Bitonic Subsequence", "Hard", ["Amazon", "Microsoft", "Google"], 1, None,
     "longest-bitonic-subsequence", None),
    (32, "dp", "Egg Dropping Puzzle", "Hard", ["Samsung", "Philips", "Myntra"], 11, 887,
     "super-egg-drop", "dp_2d"),

    # ---------- Day 33: Greedy ----------
    (33, "greedy", "Assign Cookies", "Easy", ["Amazon", "Google", "Adobe"], 1, 455,
     "assign-cookies", None),
    (33, "greedy", "Minimum Coins (Indian Coins)", "Easy",
     ["Microsoft", "Morgan Stanley", "Visa"], 8, None, "minimum-coins-indian", None),
    (33, "greedy", "Fractional Knapsack", "Medium", ["Microsoft"], 0, None,
     "fractional-knapsack", None),
    (33, "greedy", "Job Sequencing / Scheduling", "Medium", ["Microsoft", "Adobe", "Airbnb"], 1,
     None, "job-sequencing", None),
    (33, "greedy", "Activity Selection", "Medium", ["Microsoft", "Amazon", "Google"], 1, None,
     "activity-selection", None),
    (33, "greedy", "Maximum Length of Pair Chain", "Medium",
     ["Amazon", "Bloomberg", "Microsoft"], 2, 646, "maximum-length-of-pair-chain", None),

    # ---------- Day 34: Bit Manipulation & Math ----------
    (34, "bit_math", "Subsets (Power Set)", "Medium", ["Google", "Adobe", "Atlassian"], 3, 78,
     "subsets", "backtracking"),
    (34, "bit_math", "Maximum XOR of Two Numbers in an Array", "Medium",
     ["Goldman Sachs", "Google", "Amazon"], 1, 421, "maximum-xor-of-two-numbers-in-an-array",
     None),
    (34, "bit_math", "Power of Two", "Easy", ["Adobe", "Snapdeal", "TCS"], 2, 231, "power-of-two",
     None),
    (34, "bit_math", "XOR Beauty of Array", "Medium", ["Amazon"], 0, 2527, "find-xor-beauty-of-array",
     None),
    (34, "bit_math", "Watering Plants II", "Medium", ["Google"], 0, 2105, "watering-plants-ii",
     "two_pointers"),
]


def rows() -> list[dict[str, Any]]:
    """The sheet as dicts, with pattern resolved."""
    out: list[dict[str, Any]] = []
    for day, topic, title, difficulty, companies, extra, lc, slug, pattern in SHEET:
        out.append(
            {
                "day": day,
                "topic": topic,
                "title": title,
                "difficulty": difficulty,
                "companies": companies,
                "extra": extra,
                "lc": lc,
                "slug": slug,
                "pattern": pattern or TOPIC_DEFAULT_PATTERN[topic],
                "source": "leetcode" if lc is not None else "classic",
            }
        )
    return out
