"""Static seed data. Every problem below is a real LeetCode problem —
number, title, slug and pattern are not invented (build prompt 2.3: "never
fabricate... No invented LeetCode numbers, URLs"). This is the user's
actual 270-problem curriculum, extracted directly from the "Interview Prep"
sheet of their own source workbook (lc_number, title, pattern, difficulty
cross-checked against the sheet; is_neetcode150/is_blind75 cross-referenced
against the canonical NeetCode150 and Blind75 title lists).

Company frequency data does not exist for this set, so it is left out
entirely rather than guessed (design doc 5.2: "Netflix and OpenAI: no
data exists. NULL, never invented" — the same rule applies here to every
problem, not just those two companies, since no real frequency survey
backs this data).

Columns: (lc_number, title, slug, pattern, difficulty, is_neetcode150, is_blind75)
"""

PROBLEMS: list[tuple[int, str, str, str, str, bool, bool]] = [
    # arrays_hashing
    (1, "Two Sum", "two-sum", "arrays_hashing", "Easy", True, True),
    (242, "Valid Anagram", "valid-anagram", "arrays_hashing", "Easy", True, True),
    (217, "Contains Duplicate", "contains-duplicate", "arrays_hashing", "Easy", True, True),
    (169, "Majority Element", "majority-element", "arrays_hashing", "Easy", False, False),
    (303, "Range Sum Query - Immutable", "range-sum-query-immutable", "arrays_hashing", "Easy", False, False),
    (392, "Is Subsequence", "is-subsequence", "arrays_hashing", "Easy", False, False),
    (448, "Find All Numbers Disappeared in An Array", "find-all-numbers-disappeared-in-an-array", "arrays_hashing", "Easy", False, False),
    (14, "Longest Common Prefix", "longest-common-prefix", "arrays_hashing", "Easy", False, False),
    (27, "Remove Element", "remove-element", "arrays_hashing", "Easy", False, False),
    (28, "Find The Index of The First Occurrence in a String", "find-the-index-of-the-first-occurrence-in-a-string", "arrays_hashing", "Easy", False, False),
    (58, "Length of Last Word", "length-of-last-word", "arrays_hashing", "Easy", False, False),
    (118, "Pascals Triangle", "pascals-triangle", "arrays_hashing", "Easy", False, False),
    (205, "Isomorphic Strings", "isomorphic-strings", "arrays_hashing", "Easy", False, False),
    (290, "Word Pattern", "word-pattern", "arrays_hashing", "Easy", False, False),
    (496, "Next Greater Element I", "next-greater-element-i", "arrays_hashing", "Easy", False, False),
    (605, "Can Place Flowers", "can-place-flowers", "arrays_hashing", "Easy", False, False),
    (705, "Design HashSet", "design-hashset", "arrays_hashing", "Easy", False, False),
    (706, "Design HashMap", "design-hashmap", "arrays_hashing", "Easy", False, False),
    (724, "Find Pivot Index", "find-pivot-index", "arrays_hashing", "Easy", False, False),
    (929, "Unique Email Addresses", "unique-email-addresses", "arrays_hashing", "Easy", False, False),
    (1189, "Maximum Number of Balloons", "maximum-number-of-balloons", "arrays_hashing", "Easy", False, False),
    (1299, "Replace Elements With Greatest Element On Right Side", "replace-elements-with-greatest-element-on-right-side", "arrays_hashing", "Easy", False, False),
    (1603, "Design Parking System", "design-parking-system", "arrays_hashing", "Easy", False, False),
    (128, "Longest Consecutive Sequence", "longest-consecutive-sequence", "arrays_hashing", "Medium", True, True),
    (49, "Group Anagrams", "group-anagrams", "arrays_hashing", "Medium", True, True),
    (347, "Top K Frequent Elements", "top-k-frequent-elements", "arrays_hashing", "Medium", True, True),
    (238, "Product of Array Except Self", "product-of-array-except-self", "arrays_hashing", "Medium", True, True),
    (271, "Encode and Decode Strings", "encode-and-decode-strings", "arrays_hashing", "Medium", True, True),
    (75, "Sort Colors", "sort-colors", "arrays_hashing", "Medium", False, False),
    (36, "Valid Sudoku", "valid-sudoku", "arrays_hashing", "Medium", True, False),
    (41, "First Missing Positive", "first-missing-positive", "arrays_hashing", "Hard", False, False),
    # two_pointers
    (125, "Valid Palindrome", "valid-palindrome", "two_pointers", "Easy", True, True),
    (283, "Move Zeroes", "move-zeroes", "two_pointers", "Easy", False, False),
    (26, "Remove Duplicates From Sorted Array", "remove-duplicates-from-sorted-array", "two_pointers", "Easy", False, False),
    (88, "Merge Sorted Array", "merge-sorted-array", "two_pointers", "Easy", False, False),
    (15, "3Sum", "3sum", "two_pointers", "Medium", True, True),
    (11, "Container With Most Water", "container-with-most-water", "two_pointers", "Medium", True, True),
    (189, "Rotate Array", "rotate-array", "two_pointers", "Medium", False, False),
    (167, "Two Sum II Input Array Is Sorted", "two-sum-ii-input-array-is-sorted", "two_pointers", "Medium", False, False),
    (42, "Trapping Rain Water", "trapping-rain-water", "two_pointers", "Hard", True, False),
    # sliding_window
    (121, "Best Time to Buy And Sell Stock", "best-time-to-buy-and-sell-stock", "sliding_window", "Easy", True, True),
    (3, "Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", "sliding_window", "Medium", True, True),
    (424, "Longest Repeating Character Replacement", "longest-repeating-character-replacement", "sliding_window", "Medium", True, True),
    (904, "Fruits into Basket", "fruit-into-baskets", "sliding_window", "Medium", False, False),
    (209, "Minimum Size Subarray Sum", "minimum-size-subarray-sum", "sliding_window", "Medium", False, False),
    (567, "Permutation In String", "permutation-in-string", "sliding_window", "Medium", True, False),
    (76, "Minimum Window Substring", "minimum-window-substring", "sliding_window", "Hard", True, True),
    (239, "Sliding Window Maximum", "sliding-window-maximum", "sliding_window", "Hard", True, False),
    # stack
    (20, "Valid Parentheses", "valid-parentheses", "stack", "Easy", True, True),
    (225, "Implement Stack Using Queues", "implement-stack-using-queues", "stack", "Easy", False, False),
    (682, "Baseball Game", "baseball-game", "stack", "Easy", False, False),
    (22, "Generate Parentheses", "generate-parentheses", "stack", "Medium", True, False),
    (150, "Evaluate Reverse Polish Notation", "evaluate-reverse-polish-notation", "stack", "Medium", True, False),
    (155, "Min Stack", "min-stack", "stack", "Medium", True, False),
    (739, "Daily Temperatures", "daily-temperatures", "stack", "Medium", True, False),
    (853, "Car Fleet", "car-fleet", "stack", "Medium", True, False),
    (895, "Maximum Frequency Stack", "maximum-frequency-stack", "stack", "Hard", False, False),
    (84, "Largest Rectangle In Histogram", "largest-rectangle-in-histogram", "stack", "Hard", True, False),
    # binary_search
    (704, "Binary Search", "binary-search", "binary_search", "Easy", True, False),
    (977, "Squares of a Sorted Array", "squares-of-a-sorted-array", "binary_search", "Easy", False, False),
    (35, "Search Insert Position", "search-insert-position", "binary_search", "Easy", False, False),
    (69, "Sqrt(x)", "sqrtx", "binary_search", "Easy", False, False),
    (33, "Search In Rotated Sorted Array", "search-in-rotated-sorted-array", "binary_search", "Medium", True, True),
    (153, "Find Minimum In Rotated Sorted Array", "find-minimum-in-rotated-sorted-array", "binary_search", "Medium", True, True),
    (162, "Find Peak Element", "find-peak-element", "binary_search", "Medium", False, False),
    (74, "Search a 2D Matrix", "search-a-2d-matrix", "binary_search", "Medium", True, False),
    (81, "Search In Rotated Sorted Array II", "search-in-rotated-sorted-array-ii", "binary_search", "Medium", False, False),
    (875, "Koko Eating Bananas", "koko-eating-bananas", "binary_search", "Medium", True, False),
    (981, "Time Based Key Value Store", "time-based-key-value-store", "binary_search", "Medium", False, False),
    (4, "Median of Two Sorted Arrays", "median-of-two-sorted-arrays", "binary_search", "Hard", True, False),
    # linked_list
    (21, "Merge Two Sorted Lists", "merge-two-sorted-lists", "linked_list", "Easy", True, True),
    (206, "Reverse Linked List", "reverse-linked-list", "linked_list", "Easy", True, True),
    (141, "Linked List Cycle", "linked-list-cycle", "linked_list", "Easy", True, True),
    (876, "Middle of the Linked List", "middle-of-the-linked-list", "linked_list", "Easy", False, False),
    (234, "Palindrome Linked List", "palindrome-linked-list", "linked_list", "Easy", False, False),
    (143, "Reorder List", "reorder-list", "linked_list", "Medium", True, True),
    (19, "Remove Nth Node From End of List", "remove-nth-node-from-end-of-list", "linked_list", "Medium", True, True),
    (2, "Add Two Numbers", "add-two-numbers", "linked_list", "Medium", True, False),
    (287, "Find The Duplicate Number", "find-the-duplicate-number", "linked_list", "Medium", True, False),
    (61, "Rotate List", "rotate-list", "linked_list", "Medium", False, False),
    (148, "Sort List", "sort-list", "linked_list", "Medium", False, False),
    (138, "Copy List With Random Pointer", "copy-list-with-random-pointer", "linked_list", "Medium", True, False),
    (146, "LRU Cache", "lru-cache", "linked_list", "Medium", True, False),
    (23, "Merge K Sorted Lists", "merge-k-sorted-lists", "linked_list", "Hard", True, True),
    (25, "Reverse Nodes In K Group", "reverse-nodes-in-k-group", "linked_list", "Hard", False, False),
    # trees
    (104, "Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree", "trees", "Easy", True, True),
    (100, "Same Tree", "same-tree", "trees", "Easy", True, True),
    (226, "Invert Binary Tree", "invert-binary-tree", "trees", "Easy", True, True),
    (572, "Subtree of Another Tree", "subtree-of-another-tree", "trees", "Easy", True, True),
    (94, "Binary Tree Inorder Traversal", "binary-tree-inorder-traversal", "trees", "Easy", False, False),
    (101, "Symmetric Tree", "symmetric-tree", "trees", "Easy", False, False),
    (108, "Convert Sorted Array to Binary Search Tree", "convert-sorted-array-to-binary-search-tree", "trees", "Easy", False, False),
    (110, "Balanced Binary Tree", "balanced-binary-tree", "trees", "Easy", True, False),
    (112, "Path Sum", "path-sum", "trees", "Easy", False, False),
    (144, "Binary Tree Preorder Traversal", "binary-tree-preorder-traversal", "trees", "Easy", False, False),
    (145, "Binary Tree Postorder Traversal", "binary-tree-postorder-traversal", "trees", "Easy", False, False),
    (543, "Diameter of Binary Tree", "diameter-of-binary-tree", "trees", "Easy", True, False),
    (105, "Construct Binary Tree From Preorder And Inorder Traversal", "construct-binary-tree-from-preorder-and-inorder-traversal", "trees", "Medium", True, True),
    (98, "Validate Binary Search Tree", "validate-binary-search-tree", "trees", "Medium", True, True),
    (102, "Binary Tree Level Order Traversal", "binary-tree-level-order-traversal", "trees", "Medium", True, True),
    (230, "Kth Smallest Element In a Bst", "kth-smallest-element-in-a-bst", "trees", "Medium", True, True),
    (235, "Lowest Common Ancestor of a Binary Search Tree", "lowest-common-ancestor-of-a-binary-search-tree", "trees", "Medium", True, True),
    (199, "Binary Tree Right Side View", "binary-tree-right-side-view", "trees", "Medium", True, False),
    (103, "Binary Tree Zigzag Level Order Traversal", "binary-tree-zigzag-level-order-traversal", "trees", "Medium", False, False),
    (662, "Maximum Width of Binary Tree", "maximum-width-of-binary-tree", "trees", "Medium", False, False),
    (1448, "Count Good Nodes In Binary Tree", "count-good-nodes-in-binary-tree", "trees", "Medium", True, False),
    (124, "Binary Tree Maximum Path Sum", "binary-tree-maximum-path-sum", "trees", "Hard", True, True),
    (297, "Serialize And Deserialize Binary Tree", "serialize-and-deserialize-binary-tree", "trees", "Hard", True, True),
    # tries
    (208, "Implement Trie Prefix Tree", "implement-trie-prefix-tree", "tries", "Medium", False, False),
    (211, "Design Add And Search Words Data Structure", "design-add-and-search-words-data-structure", "tries", "Medium", True, True),
    (212, "Word Search II", "word-search-ii", "tries", "Hard", True, True),
    # heap
    (703, "Kth Largest Element In a Stream", "kth-largest-element-in-a-stream", "heap", "Easy", True, False),
    (1046, "Last Stone Weight", "last-stone-weight", "heap", "Easy", True, False),
    (767, "Reorganize String", "reorganize-string", "heap", "Medium", False, False),
    (215, "Kth Largest Element In An Array", "kth-largest-element-in-an-array", "heap", "Medium", True, False),
    (621, "Task Scheduler", "task-scheduler", "heap", "Medium", True, False),
    (973, "K Closest Points to Origin", "k-closest-points-to-origin", "heap", "Medium", True, False),
    (355, "Design Twitter", "design-twitter", "heap", "Medium", True, False),
    (1094, "Car Pooling", "car-pooling", "heap", "Medium", False, False),
    (1405, "Longest Happy String", "longest-happy-string", "heap", "Medium", False, False),
    (1834, "Single Threaded Cpu", "single-threaded-cpu", "heap", "Medium", False, False),
    (1845, "Seat Reservation Manager", "seat-reservation-manager", "heap", "Medium", False, False),
    (1882, "Process Tasks Using Servers", "process-tasks-using-servers", "heap", "Medium", False, False),
    (295, "Find Median From Data Stream", "find-median-from-data-stream", "heap", "Hard", True, True),
    # backtracking
    (79, "Word Search", "word-search", "backtracking", "Medium", True, True),
    (39, "Combination Sum", "combination-sum", "backtracking", "Medium", True, False),
    (17, "Letter Combinations of a Phone Number", "letter-combinations-of-a-phone-number", "backtracking", "Medium", True, False),
    (78, "Subsets", "subsets", "backtracking", "Medium", True, False),
    (46, "Permutations", "permutations", "backtracking", "Medium", True, False),
    (131, "Palindrome Partitioning", "palindrome-partitioning", "backtracking", "Medium", True, False),
    (77, "Combinations", "combinations", "backtracking", "Medium", False, False),
    (90, "Subsets II", "subsets-ii", "backtracking", "Medium", True, False),
    (47, "Permutations II", "permutations-ii", "backtracking", "Medium", False, False),
    (40, "Combination Sum II", "combination-sum-ii", "backtracking", "Medium", True, False),
    (698, "Partition to K Equal Sum Subsets", "partition-to-k-equal-sum-subsets", "backtracking", "Medium", False, False),
    (93, "Restore IP Addresses", "restore-ip-addresses", "backtracking", "Medium", False, False),
    (51, "N Queens", "n-queens", "backtracking", "Hard", False, False),
    # graphs
    (463, "Island Perimeter", "island-perimeter", "graphs", "Easy", False, False),
    (953, "Verifying An Alien Dictionary", "verifying-an-alien-dictionary", "graphs", "Easy", False, False),
    (200, "Number of Islands", "number-of-islands", "graphs", "Medium", True, True),
    (207, "Course Schedule", "course-schedule", "graphs", "Medium", True, True),
    (417, "Pacific Atlantic Water Flow", "pacific-atlantic-water-flow", "graphs", "Medium", True, True),
    (133, "Clone Graph", "clone-graph", "graphs", "Medium", True, True),
    (261, "Graph Valid Tree", "graph-valid-tree", "graphs", "Medium", True, True),
    (323, "Number of Connected Components In An Undirected Graph", "number-of-connected-components-in-an-undirected-graph", "graphs", "Medium", True, True),
    (210, "Course Schedule II", "course-schedule-ii", "graphs", "Medium", True, False),
    (130, "Surrounded Regions", "surrounded-regions", "graphs", "Medium", True, False),
    (286, "Walls And Gates", "walls-and-gates", "graphs", "Medium", True, False),
    (399, "Evaluate Division", "evaluate-division", "graphs", "Medium", False, False),
    (684, "Redundant Connection", "redundant-connection", "graphs", "Medium", True, False),
    (695, "Max Area of Island", "max-area-of-island", "graphs", "Medium", True, False),
    (721, "Accounts Merge", "accounts-merge", "graphs", "Medium", False, False),
    (752, "Open The Lock", "open-the-lock", "graphs", "Medium", False, False),
    (785, "Is Graph Bipartite?", "is-graph-bipartite", "graphs", "Medium", False, False),
    (802, "Find Eventual Safe States", "find-eventual-safe-states", "graphs", "Medium", False, False),
    (909, "Snakes And Ladders", "snakes-and-ladders", "graphs", "Medium", False, False),
    (934, "Shortest Bridge", "shortest-bridge", "graphs", "Medium", False, False),
    (994, "Rotting Oranges", "rotting-oranges", "graphs", "Medium", True, False),
    (1020, "Number of Enclaves", "number-of-enclaves", "graphs", "Medium", False, False),
    (1091, "Shortest Path in Binary Matrix", "shortest-path-in-binary-matrix", "graphs", "Medium", False, False),
    (1129, "Shortest Path with Alternating Colors", "shortest-path-with-alternating-colors", "graphs", "Medium", False, False),
    (1162, "As Far from Land as Possible", "as-far-from-land-as-possible", "graphs", "Medium", False, False),
    (1254, "Number of Closed Islands", "number-of-closed-islands", "graphs", "Medium", False, False),
    (127, "Word Ladder", "word-ladder", "graphs", "Hard", True, False),
    # advanced_graphs
    (743, "Network Delay Time", "network-delay-time", "advanced_graphs", "Medium", True, False),
    (787, "Cheapest Flights Within K Stops", "cheapest-flights-within-k-stops", "advanced_graphs", "Medium", True, False),
    (1514, "Path with Maximum Probability", "path-with-maximum-probability", "advanced_graphs", "Medium", False, False),
    (1584, "Min Cost to Connect All Points", "min-cost-to-connect-all-points", "advanced_graphs", "Medium", True, False),
    (1631, "Path with Minimum Effort", "path-with-minimum-effort", "advanced_graphs", "Medium", False, False),
    (269, "Alien Dictionary", "alien-dictionary", "advanced_graphs", "Hard", True, True),
    (332, "Reconstruct Itinerary", "reconstruct-itinerary", "advanced_graphs", "Hard", True, False),
    (778, "Swim In Rising Water", "swim-in-rising-water", "advanced_graphs", "Hard", True, False),
    # dp_1d
    (70, "Climbing Stairs", "climbing-stairs", "dp_1d", "Easy", True, True),
    (746, "Min Cost Climbing Stairs", "min-cost-climbing-stairs", "dp_1d", "Easy", True, False),
    (1137, "N-th Tribonacci Number", "n-th-tribonacci-number", "dp_1d", "Easy", False, False),
    (5, "Longest Palindromic Substring", "longest-palindromic-substring", "dp_1d", "Medium", True, True),
    (198, "House Robber", "house-robber", "dp_1d", "Medium", True, True),
    (322, "Coin Change", "coin-change", "dp_1d", "Medium", True, True),
    (152, "Maximum Product Subarray", "maximum-product-subarray", "dp_1d", "Medium", True, True),
    (139, "Word Break", "word-break", "dp_1d", "Medium", True, True),
    (647, "Palindromic Substrings", "palindromic-substrings", "dp_1d", "Medium", True, True),
    (300, "Longest Increasing Subsequence", "longest-increasing-subsequence", "dp_1d", "Medium", True, True),
    (213, "House Robber II", "house-robber-ii", "dp_1d", "Medium", True, True),
    (91, "Decode Ways", "decode-ways", "dp_1d", "Medium", True, True),
    (416, "Partition Equal Subset Sum", "partition-equal-subset-sum", "dp_1d", "Medium", True, False),
    (377, "Combination Sum IV", "combination-sum-iv", "dp_1d", "Medium", False, True),
    (673, "Number of Longest Increasing Subsequence", "number-of-longest-increasing-subsequence", "dp_1d", "Medium", False, False),
    (120, "Triangle", "triangle", "dp_1d", "Medium", False, False),
    (256, "Paint House", "paint-house", "dp_1d", "Medium", False, False),
    (279, "Perfect Squares", "perfect-squares", "dp_1d", "Medium", False, False),
    (343, "Integer Break", "integer-break", "dp_1d", "Medium", False, False),
    (740, "Delete And Earn", "delete-and-earn", "dp_1d", "Medium", False, False),
    (837, "New 21 Game", "new-21-game", "dp_1d", "Medium", False, False),
    (983, "Minimum Cost For Tickets", "minimum-cost-for-tickets", "dp_1d", "Medium", False, False),
    (1035, "Uncrossed Lines", "uncrossed-lines", "dp_1d", "Medium", False, False),
    (472, "Concatenated Words", "concatenated-words", "dp_1d", "Hard", False, False),
    # dp_2d
    (62, "Unique Paths", "unique-paths", "dp_2d", "Medium", True, True),
    (1143, "Longest Common Subsequence", "longest-common-subsequence", "dp_2d", "Medium", True, True),
    (494, "Target Sum", "target-sum", "dp_2d", "Medium", True, False),
    (309, "Best Time to Buy And Sell Stock With Cooldown", "best-time-to-buy-and-sell-stock-with-cooldown", "dp_2d", "Medium", True, False),
    (63, "Unique Paths II", "unique-paths-ii", "dp_2d", "Medium", False, False),
    (64, "Minimum Path Sum", "minimum-path-sum", "dp_2d", "Medium", False, False),
    (72, "Edit Distance", "edit-distance", "dp_2d", "Medium", True, False),
    (97, "Interleaving String", "interleaving-string", "dp_2d", "Medium", True, False),
    (221, "Maximal Square", "maximal-square", "dp_2d", "Medium", False, False),
    (474, "Ones and Zeroes", "ones-and-zeroes", "dp_2d", "Medium", False, False),
    (516, "Longest Palindromic Subsequence", "longest-palindromic-subsequence", "dp_2d", "Medium", False, False),
    (518, "Coin Change II", "coin-change-ii", "dp_2d", "Medium", True, False),
    (877, "Stone Game", "stone-game", "dp_2d", "Medium", False, False),
    (926, "Flip String to Monotone Increasing", "flip-string-to-monotone-increasing", "dp_2d", "Medium", False, False),
    (1049, "Last Stone Weight II", "last-stone-weight-ii", "dp_2d", "Medium", False, False),
    (1140, "Stone Game II", "stone-game-ii", "dp_2d", "Medium", False, False),
    (10, "Regular Expression Matching", "regular-expression-matching", "dp_2d", "Hard", True, False),
    (115, "Distinct Subsequences", "distinct-subsequences", "dp_2d", "Hard", True, False),
    (312, "Burst Balloons", "burst-balloons", "dp_2d", "Hard", True, False),
    (329, "Longest Increasing Path In a Matrix", "longest-increasing-path-in-a-matrix", "dp_2d", "Hard", True, False),
    # greedy
    (53, "Maximum Subarray", "maximum-subarray", "greedy", "Medium", True, True),
    (55, "Jump Game", "jump-game", "greedy", "Medium", True, True),
    (134, "Gas Station", "gas-station", "greedy", "Medium", True, False),
    (45, "Jump Game II", "jump-game-ii", "greedy", "Medium", True, False),
    (646, "Maximum Length of Pair Chain", "maximum-length-of-pair-chain", "greedy", "Medium", False, False),
    (649, "Dota2 Senate", "dota2-senate", "greedy", "Medium", False, False),
    (678, "Valid Parenthesis String", "valid-parenthesis-string", "greedy", "Medium", True, False),
    (763, "Partition Labels", "partition-labels", "greedy", "Medium", True, False),
    (846, "Hand of Straights", "hand-of-straights", "greedy", "Medium", True, False),
    (918, "Maximum Sum Circular Subarray", "maximum-sum-circular-subarray", "greedy", "Medium", False, False),
    (978, "Longest Turbulent Array", "longest-turbulent-subarray", "greedy", "Medium", False, False),
    (1029, "Two City Scheduling", "two-city-scheduling", "greedy", "Medium", False, False),
    (1423, "Maximum Points You Can Obtain From Cards", "maximum-points-you-can-obtain-from-cards", "greedy", "Medium", False, False),
    (1647, "Minimum Deletions to Make Character Frequencies Unique", "minimum-deletions-to-make-character-frequencies-unique", "greedy", "Medium", False, False),
    (1871, "Jump Game VII", "jump-game-vii", "greedy", "Medium", False, False),
    (1899, "Merge Triplets to Form Target Triplet", "merge-triplets-to-form-target-triplet", "greedy", "Medium", True, False),
    (1921, "Eliminate Maximum Number of Monsters", "eliminate-maximum-number-of-monsters", "greedy", "Medium", False, False),
    # intervals
    (252, "Meeting Rooms", "meeting-rooms", "intervals", "Easy", True, True),
    (56, "Merge Intervals", "merge-intervals", "intervals", "Medium", True, True),
    (253, "Meeting Rooms II", "meeting-rooms-ii", "intervals", "Medium", True, True),
    (435, "Non Overlapping Intervals", "non-overlapping-intervals", "intervals", "Medium", False, False),
    (57, "Insert Interval", "insert-interval", "intervals", "Medium", True, True),
    (1288, "Remove Covered Intervals", "remove-covered-intervals", "intervals", "Medium", False, False),
    (352, "Data Stream as Disjoint Intervals", "data-stream-as-disjoint-intervals", "intervals", "Hard", False, False),
    (1851, "Minimum Interval to Include Each Query", "minimum-interval-to-include-each-query", "intervals", "Hard", True, False),
    # math_geometry
    (9, "Palindrome Number", "palindrome-number", "math_geometry", "Easy", False, False),
    (13, "Roman to Integer", "roman-to-integer", "math_geometry", "Easy", False, False),
    (66, "Plus One", "plus-one", "math_geometry", "Easy", True, False),
    (168, "Excel Sheet Column Title", "excel-sheet-column-title", "math_geometry", "Easy", False, False),
    (202, "Happy Number", "happy-number", "math_geometry", "Easy", True, False),
    (263, "Ugly Number", "ugly-number", "math_geometry", "Easy", False, False),
    (1071, "Greatest Common Divisor of Strings", "greatest-common-divisor-of-strings", "math_geometry", "Easy", False, False),
    (1260, "Shift 2D Grid", "shift-2d-grid", "math_geometry", "Easy", False, False),
    (1523, "Count Odd Numbers in an Interval Range", "count-odd-numbers-in-an-interval-range", "math_geometry", "Easy", False, False),
    (1572, "Matrix Diagonal Sum", "matrix-diagonal-sum", "math_geometry", "Easy", False, False),
    (54, "Spiral Matrix", "spiral-matrix", "math_geometry", "Medium", True, True),
    (48, "Rotate Image", "rotate-image", "math_geometry", "Medium", True, True),
    (73, "Set Matrix Zeroes", "set-matrix-zeroes", "math_geometry", "Medium", True, True),
    (6, "Zigzag Conversion", "zigzag-conversion", "math_geometry", "Medium", False, False),
    (12, "Integer to Roman", "integer-to-roman", "math_geometry", "Medium", False, False),
    (43, "Multiply Strings", "multiply-strings", "math_geometry", "Medium", True, False),
    (50, "Pow(x, n)", "powx-n", "math_geometry", "Medium", True, False),
    (59, "Spiral Matrix II", "spiral-matrix-ii", "math_geometry", "Medium", False, False),
    (1041, "Robot Bounded In Circle", "robot-bounded-in-circle", "math_geometry", "Medium", False, False),
    (2013, "Detect Squares", "detect-squares", "math_geometry", "Medium", True, False),
    # bit_manipulation
    (268, "Missing Number", "missing-number", "bit_manipulation", "Easy", True, True),
    (190, "Reverse Bits", "reverse-bits", "bit_manipulation", "Easy", True, True),
    (191, "Number of 1 Bits", "number-of-1-bits", "bit_manipulation", "Easy", True, True),
    (338, "Counting Bits", "counting-bits", "bit_manipulation", "Easy", True, True),
    (136, "Single Number", "single-number", "bit_manipulation", "Easy", True, False),
    (67, "Add Binary", "add-binary", "bit_manipulation", "Easy", False, False),
    (989, "Add to Array-Form of Integer", "add-to-array-form-of-integer", "bit_manipulation", "Easy", False, False),
    (371, "Sum of Two Integers", "sum-of-two-integers", "bit_manipulation", "Medium", True, True),
    (7, "Reverse Integer", "reverse-integer", "bit_manipulation", "Medium", True, False),
]

# Cues are this seed's own summary, not quoted from any external source.
PATTERNS: list[tuple[str, str]] = [
    ("arrays_hashing", "Need O(1) lookup/count, or a frequency map, over a flat collection."),
    ("two_pointers", "Sorted (or sortable) sequence; converging or same-direction pointers."),
    ("sliding_window", "Contiguous subarray/substring with a size or validity condition."),
    ("stack", "Nested structure, matching pairs, or 'next greater/smaller' queries."),
    ("binary_search", "Monotonic search space, even if not an obviously sorted array."),
    ("linked_list", "Pointer manipulation, cycle detection, or in-place reversal."),
    ("trees", "Recursive structure with a parent/child relationship to traverse."),
    ("tries", "Prefix matching across many strings."),
    ("heap", "Repeatedly need the current min/max as the set changes."),
    ("backtracking", "Build a candidate incrementally, prune, and undo a choice."),
    ("graphs", "Explicit or implicit graph — grid, adjacency list, or dependency order."),
    ("advanced_graphs", "Weighted shortest-path, MST, or union-find over a graph."),
    ("dp_1d", "Optimal choice at position i depends on a fixed window of prior positions."),
    ("dp_2d", "Optimal choice depends on two indices — grid or two-sequence comparison."),
    ("greedy", "A locally optimal choice at each step provably yields the global optimum."),
    ("intervals", "Overlapping ranges — sort by start or end, then sweep."),
    ("math_geometry", "Direct simulation or number-theoretic reasoning, no clear DS pattern."),
    ("bit_manipulation", "Constant-space arithmetic via bit tricks."),
]

OPERATING_RULES: list[tuple[str, str, str]] = [
    (
        "minimum_viable_day",
        "On a day with under 20 minutes of real bandwidth: clear at most a "
        "handful of overdue reviews or five vocabulary words. Do not start a "
        "new problem. A Minimum Viable Day still counts as a day kept.",
        "bandwidth",
    ),
    (
        "review_cap_overflow",
        "The daily review cap defaults to 12. Overflow order is failed "
        "reviews first, then oldest-overdue, then due-today; the remainder "
        "pushes one day and its overdue_days counter increments. Nothing is "
        "ever silently dropped.",
        "repetition",
    ),
    (
        "pattern_interleaving",
        "Never more than 2 consecutive recommended problems from the same "
        "pattern once past the foundation phase — blocked practice inflates "
        "apparent mastery.",
        "recommender",
    ),
]
